// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtB6pxgSpivXo8qQxa6TBuLUp53oho_08',
    appId: '1:264976116975:web:80a3a3e498603a54a37f1a',
    messagingSenderId: '264976116975',
    projectId: 'cheery-28b8a',
    authDomain: 'cheery-28b8a.firebaseapp.com',
    storageBucket: 'cheery-28b8a.firebasestorage.app',
    measurementId: 'G-4E9SVP59MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4YXz2ghB14peETLDV-4WvgZJtT4hm1QY',
    appId: '1:264976116975:android:a7a24ad9efc020c5a37f1a',
    messagingSenderId: '264976116975',
    projectId: 'cheery-28b8a',
    storageBucket: 'cheery-28b8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFAm49uZur1PDQjNPFizGL7_0uVuEO5I',
    appId: '1:264976116975:ios:ff09fab0fb354a49a37f1a',
    messagingSenderId: '264976116975',
    projectId: 'cheery-28b8a',
    storageBucket: 'cheery-28b8a.firebasestorage.app',
    iosBundleId: 'com.cheeryhq.app',
  );
}
